version: "3.9"

services:
  status-page:
    build: .
    container_name: status-page
    # ports:
    #   - "8080:3000"
    volumes:
      - /opt/uptime/data:/app/data
    environment:
      - TZ=Asia/Colombo
    restart: unless-stopped
